[project]
name = "model"
version = "0.1.0"
description = "A machine learning model for predicting outcomes based on input data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "xgboost>=3.2.0",
]
